Chore:  Add custom ESLint and Prettier configs
naomi-lgbt/fruit pull request #10
Opened 2023-12-16 21:55 UTC by a2937

# Pull Request

## Description:

I followed the instructions given on the issue and did my best to tidy things up and fill in JSDocs. However I keep having an issue resolving the module `'@angular/common/http'`. I suspect it's probably an issue with my local computer though as I did see @angular/common listed on the package.json. 

## Related Issue:

Closes #9

2023-12-16 23:54 UTC, naomi-lgbt requested changes

2023-12-16 23:54 UTC, naomi-lgbt commented on .eslintrc.json
> +  "extends": "@nhcarrigan/eslint-config-angular"
```suggestion
  "extends": "@nhcarrigan/eslint-config-angular",
  "rules": {
    // TODO: Remove once the package is updated.
    "import/no-unresolved": "off"
  }
```

This rule is broken in the package oops - we'll need to fix this over there.

2023-12-17 00:09 UTC, a2937 commented on .eslintrc.json
> +  "extends": "@nhcarrigan/eslint-config-angular"
Naomi, can you help explain why the module didn't resolve? It'd be helpful for me going forward.

2023-12-17 04:34 UTC, naomi-lgbt commented on .eslintrc.json
> +  "extends": "@nhcarrigan/eslint-config-angular"
If I had to venture a guess, it's either due to the way the deeply nested exports are handled, or the way pnpm resolves the node_modules via symlink.

2023-12-17 04:36 UTC, naomi-lgbt approved these changes

2023-12-17 04:36 UTC, merged